name: Build & Publish (Windows → itch.io)

on:
  workflow_dispatch:
  push:
    branches: [main]      # deploy on main
    tags:     ["v*"]      # …and version tags

env:
  # Match your existing web workflow’s version
  GODOT_VERSION: "4.4.1-stable"
  # If you prefer, move these to “Repository variables”
  ITCHIO_USERNAME: "jonaswills"
  ITCHIO_GAME: "cozy-cook"
  WINDOWS_PRESET: "Windows"   # must match preset name in Godot

jobs:
  windows:
    runs-on: ubuntu-latest

    # Use the godot-ci image so Godot + templates are ready
    # (this is the official container from the marketplace action)
    container:
      image: barichello/godot-ci:4.4.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Optional: warm the import cache for clean runners
      - name: Prime .godot import cache (non-fatal)
        run: |
          # Ensures reimports don't stall on headless
          godot --headless --editor --quit || true

      - name: Export Windows (Release)
        run: |
          mkdir -p "builds/windows"
          # Uses your Windows export preset; output path can be different from preset's
          godot --verbose --headless --export-release "${WINDOWS_PRESET}" \
            "builds/windows/Cozy Cook/Cozy Cook.exe"

      - name: Zip Windows build
        run: |
          cd "builds/windows"
          zip -r ../cozy_cook_windows.zip .
          cd - 

      - name: Install butler
        run: |
          curl -L https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default > butler.zip
          unzip -oq butler.zip -d $HOME/.local/bin
          chmod +x $HOME/.local/bin/butler

      - name: Compute version label
        id: ver
        shell: bash
        run: |
          if [ -f VERSION.txt ]; then
            echo "v=$(cat VERSION.txt)" >> $GITHUB_OUTPUT
          else
            # strip leading 'refs/tags/' and use the tag (v1.2.3)
            echo "v=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: "Push to itch.io (channel: windows)"
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          $HOME/.local/bin/butler push buicozy_cook_windowsows.zip \
            "${ITCHIO_USERNAME}/${ITCHIO_GAME}:windows" \
            --userversion "${{ steps.ver.outputs.v }}"
